### ISSUE TITLE
valori dei blocchi forgiati tutti uguali entrando nella pagina di un delegato qualsiasi

### ISSUE THREAD

**Issue by corsaro1** [dakk/shift-lobbby#20]
Period	Forged LSK	Forged BTC	Forged USD	Forged EUR
Today	5430.71485255	0.9963189468488229	768.1619080204425	738.2723396149778
Last 24h	5430.71485255	0.9963189468488229	768.1619080204425	738.2723396149778
Last 7 days	5430.71485255	0.9963189468488229	768.1619080204425	738.2723396149778
Last 30 days	5430.71485255	0.9963189468488229	768.1619080204425	738.2723396149778
All time	5430.71485255	0.9963189468488229	768.1619080204425	738.2723396149778

**Comment by dakk** [comment]
You need to deploy my node modification
